### ISSUE TITLE
Remove v1alpha1 in v0.31.0

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes-sigs/descheduler#1375]
v1alpha1 version of the descheduling policy has been deprecated for many releases now. It's time to remove it from the code base and focus on v1alpha3.

Removal announced on sig-scheduling dev list: https://groups.google.com/g/kubernetes-sig-scheduling/c/OyFjkDntuhg/m/GVjD4gpaBAAJ?utm_medium=email&utm_source=footer
1.30 k8s release scheduled for Wednesday 17th April 2024: https://www.kubernetes.dev/resources/release/#summary

**TODO**:
- [ ] - remove v1alpha1 types from the code
- [ ] - remove v1alpha1 -> v1alpha2 conversion code
- [ ] - remove any mention of v1alpha1 type from the documentation (probably just mentioning v1alpha1 was removed in 0.31.0)
- [ ] - announce v1alpha1 removal on sig-scheduling dev list + descheduler changelogs

**Comment by a7i** [comment]
fyi- Warning should land in v0.30 and should be noted in the release notes: https://github.com/kubernetes-sigs/descheduler/pull/1337
